language: python
cache: pip
git:
  depth: 9999999
jobs:
  include:
    - name: "Python 3.6.0 on Xenial Linux"
      os: linux
      python: 3.6
      install:
        - sudo apt-get -qq update
        - sudo apt-get install -y build-essential
        - sudo apt-get install -y libgtk-3-dev
        - pip install wxPython PyInstaller
      script:
        - cd install
        - python createapp.py Linux
    - name: "Python 3.7.4 on macOS"
      os: osx
      language: generic
      before_install:
        - brew update
        # - brew upgrade python
        - pip install wxPython PyInstaller
      script:
        - cd install
        - python createapp.py OSX
        - cd ..
        - rm bin/dist/bookmaction
        - python install/createdmg.py bookmaction bin/dist
    - name: "Python 3.8.2 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - pip install wxPython
        - pip install PyInstaller
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      script:
        - cd install
        - python createapp.py Windows
        - cd ..
deploy:
  provider: releases
  api_key:
    secure: Y7t3KLHMt177qWLx5XH8cp8pnSNH+Hdyh28/tqlmQIolS4MrtTBS4LhaMKXfIYY7bVdGUGPlxVmRpMLrzVzMeT8BHkyesvc1aD9SMOSAg8E8y1oMrP5pwF+jg+BG+QQnoOAepxcUukGmBjO9YrXolEY96N3RJT33+1jNOg49pDtyllLXccr15hoEXkz6VI+RbV2XzUP8G3T3wTG29o40+IIM75pCiZQP1bnupdsdrBC8YYMKOtkv6y4fOtYw2N9xcarmMQLRAQcKk6ympMzqBCz1agx4wBm5MdW2zXTRzC5uEXeOqKu8DnAuTTqxuIUUexiydWlyX0GptEwU5vqmvfckdn/sPid774EJKP3366/HqwN5Wvv/GRb5tiNBBF3CsuoxNrKxcbn+w17sDBVHdQ0wZhidq0BA3Z3t4ZHfA+Y7c/qf42hZxExbyS4+2c5E3bGL2fF2Bq9qAdcmIdJEdxygWfdsgT1YnDfDBKG9cGpNyXjzK2wfvZLzPMprUMVdPjjKphleu4kwbw6Tezb41n3EH9pbVX8LAdSeMcQxUc9GwPTXkUxfcKlacgzCnWIMVhd1W/8heCIMpyenuTbtbC6hHbSyRQOOZmoSIPJHU1/9dfrnwF+lODFpmYW4zwdSf12ZgIETqjo6UZr+djP1yIylj2+qfb/+T1nSYh6vEf0=
  file_glob: true
  file:
    - "*.dmg"
    - ".exe"
    - "bin/dist/bookmaction.exe"
  skip_cleanup: true
  on:
    repo: lucsch/bookmaction
    tags: true
  draft: true
